spring:
  application:
    name: myBatisDemo1
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5444/test1"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 12000
